Доработана функциональность по ТЗ спринта 6
nikitasaratovkin/java-kanban pull request #1
Opened 2024-07-24 21:00 UTC by madxCatz

Реализован новый пользовательский сценарий в классе Main. Реализовано хранение истории с помощью связного списка и хеш-таблицы. Убраны повторы в истории просмотров. Исправлена ошибка в методе checkStatus().

2024-07-25 19:21 UTC, sergeymamonov requested changes
Класс Managers. Создается константа HISTORY_MANAGER и используется только в методе getDefaultHistory. Так лучше удалить эту константу и создать InMemoryHistoryManager только к методе getDefaultHistory.

2024-07-25 19:21 UTC, sergeymamonov commented on src/InMemoryHistoryManager.java
> +    public List<Task> getTasks() {
Этот метод и метод ниже используются только в этом классе, поэтому их можно сделать приватными.

2024-07-25 19:21 UTC, sergeymamonov commented on src/InMemoryTaskManager.java
> +        int counter = -1;
Полю можно добавить модификатор доступа.

2024-07-25 19:21 UTC, sergeymamonov commented on test/ManagersTest.java
>      TaskManager manager = Managers.getDefault();
Я бы не пропускал модификаторы доступа даже в тестах. Но только не возникнет такого, что мы провели один тест, что-то добавили в историю, а потом в следующем тесте будем проверить, и окажется, что тесты влияют друг на друга. Нужно стараться писать тесты так, чтобы они не влияли друг на друга. И не зависили от порядка запуска.

2024-07-26 15:42 UTC, nikitasaratovkin commented
> Класс Managers. Создается константа HISTORY_MANAGER и используется только в методе getDefaultHistory. Так лучше удалить эту константу и создать InMemoryHistoryManager только к методе getDefaultHistory.

В классе Managers удалить константу HISTORY_MANAGER не получится, иначе возникнет следующая проблема: в классе InMemoryTaskManager создается объект-менеджер истории (historyManager = Managers.getDefaultHistory()) и работает с историей (сохраняет, удаляет и тд). В классе Main создается менеджер задач (TaskManager manager = Managers.getDefault()) и менеджер истории (HistoryManager history = Managers.getDefaultHistory()). Если сделать так, как вы предлагаете, то история, которая находится в переменной 'manager' и история в переменной 'history' будут различаться, а если точнее, то история в 'history' будет просто пустая. Чтобы такую проблему решить, я вывожу HISTORY_MANAGER в константу класса Managers, чтобы метод getDefaultHistory() выдавал мне одну и ту же историю и в классе InMemoryTaskManager и в классе Main.

2024-07-26 15:43 UTC, nikitasaratovkin commented on src/InMemoryTaskManager.java
> +        int counter = -1;
int 'counter' в методе checkStatus() - это локальная переменная. IDEA не дает добавить к этой переменной модификатор доступа

2024-07-26 20:10 UTC, sergeymamonov commented
> > Класс Managers. Создается константа HISTORY_MANAGER и используется только в методе getDefaultHistory. Так лучше удалить эту константу и создать InMemoryHistoryManager только к методе getDefaultHistory.
> 
> В классе Managers удалить константу HISTORY_MANAGER не получится, иначе возникнет следующая проблема: в классе InMemoryTaskManager создается объект-менеджер истории (historyManager = Managers.getDefaultHistory()) и работает с историей (сохраняет, удаляет и тд). В классе Main создается менеджер задач (TaskManager manager = Managers.getDefault()) и менеджер истории (HistoryManager history = Managers.getDefaultHistory()). Если сделать так, как вы предлагаете, то история, которая находится в переменной 'manager' и история в переменной 'history' будут различаться, а если точнее, то история в 'history' будет просто пустая. Чтобы такую проблему решить, я вывожу HISTORY_MANAGER в константу класса Managers, чтобы метод getDefaultHistory() выдавал мне одну и ту же историю и в классе InMemoryTaskManager и в классе Main.

Не нужно создавать HistoryManager . Достаточно HistoryManager  в классе TaskManager.

2024-07-26 20:12 UTC, sergeymamonov commented
И обратите внимание HistoryManager в классе InMemoryTaskManager называется с большой буквы, в Java camelCase.

2024-07-26 20:14 UTC, sergeymamonov approved these changes

2024-07-26 20:14 UTC, sergeymamonov commented on src/InMemoryTaskManager.java
> +        int counter = -1;
Да, конечно, это я перепутал, хотел к 8 строке поставить, но получилось здесь, извините.

2024-07-27 09:13 UTC, merged